# Generated by Django 3.0.2 on 2020-02-07 16:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=10)),
                ('dob', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(max_length=50)),
                ('website', models.URLField(blank=True, default='')),
                ('bio', models.TextField(default='')),
                ('is_verified', models.BooleanField(default=False)),
                ('user_img', models.ImageField(blank=True, upload_to='user/img')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
