# Generated by Django 3.0.2 on 2020-02-18 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('livebit', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='alt_text',
        ),
        migrations.RemoveField(
            model_name='post',
            name='location',
        ),
        migrations.RemoveField(
            model_name='post',
            name='post_img',
        ),
    ]
