# Generated by Django 3.0.2 on 2020-02-18 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('livebit', '0003_auto_20200218_2144'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
