# Generated by Django 3.0.2 on 2020-02-21 00:55

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('livebit', '0007_friend_current_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 21, 0, 55, 14, 816774, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='post',
            name='alt_text',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='caption',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='location',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
