# Generated by Django 3.0.2 on 2020-02-22 16:17

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('livebit', '0012_auto_20200222_2145'),
    ]

    operations = [
        migrations.AddField(
            model_name='posttag',
            name='post',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='post_tag', to='livebit.Post'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 22, 16, 17, 10, 82479, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='postlikes',
            name='liker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_liker', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='postlikes',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_like', to='livebit.Post'),
        ),
        migrations.AlterField(
            model_name='posttag',
            name='tagged_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_tagger', to=settings.AUTH_USER_MODEL),
        ),
    ]
