# Generated by Django 3.0.2 on 2020-02-22 16:24

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('livebit', '0016_auto_20200222_2152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 22, 16, 24, 7, 123651, tzinfo=utc)),
        ),
    ]
