# Generated by Django 3.0.2 on 2020-02-22 17:28

import datetime
from django.conf import settings
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('livebit', '0019_auto_20200222_2159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 22, 17, 28, 4, 466689, tzinfo=utc)),
        ),
        migrations.RemoveField(
            model_name='postlike',
            name='liker',
        ),
        migrations.AddField(
            model_name='postlike',
            name='liker',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
