# Generated by Django 3.0.2 on 2020-02-22 17:47

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('livebit', '0022_auto_20200222_2259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 22, 17, 46, 55, 289966, tzinfo=utc)),
        ),
    ]
