# Generated by Django 3.0.2 on 2020-02-22 18:11

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('livebit', '0023_auto_20200222_2317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 22, 18, 11, 32, 660485, tzinfo=utc)),
        ),
    ]
