# Generated by Django 3.0.2 on 2020-02-22 18:13

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('livebit', '0024_auto_20200222_2341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 22, 18, 13, 1, 569945, tzinfo=utc)),
        ),
    ]
