# Generated by Django 3.0.2 on 2020-02-25 13:55

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('livebit', '0026_auto_20200225_1834'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 25, 13, 55, 57, 967547, tzinfo=utc)),
        ),
        migrations.DeleteModel(
            name='Friend',
        ),
    ]
