# Generated by Django 3.0.2 on 2020-02-25 13:57

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('livebit', '0027_auto_20200225_1925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 25, 13, 57, 31, 195630, tzinfo=utc)),
        ),
    ]
