# Generated by Django 2.2.10 on 2020-02-28 17:02

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('livebit', '0028_auto_20200225_1927'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 28, 17, 1, 59, 872149, tzinfo=utc)),
        ),
    ]
