# Generated by Django 3.0.2 on 2020-02-07 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fact',
            fields=[
                ('fact_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=5000)),
                ('fact', models.CharField(max_length=5000)),
                ('fact_img', models.ImageField(upload_to='fact/img')),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('service_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=70)),
                ('url', models.TextField(default='')),
                ('description', models.CharField(max_length=500)),
                ('service_img', models.ImageField(upload_to='service/img')),
            ],
        ),
    ]
